title: Upeoe's blog
author: vuri
url: https://upeoe.github.io
baseurl:
remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
